# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: default

steps:
- script: |
    cd c:/nssm/win64
    nssm stop IntegrationProjectService
  displayName: 'Stopping integration service'

- powershell: |
    cd c:/IntegrationProject
    git pull origin master
  displayName: 'Updating Git repository'

- powershell: |
    cd c:/IntegrationProject
    npm install
  displayName: 'Installing dependencies'
  
- powershell: |
    cd c:/IntegrationProject
    #node .\syncReceiver.js
  displayName: 'Running application'

- script: |
    cd c:/nssm/win64
    nssm start IntegrationProjectService
  displayName: 'Starting integration service'
