# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: default

steps:
- powershell: |
    cd c:/IntegrationProject
    git fetch
    git checkout --force $BUILD_SOURCEVERSION
  displayName: 'Updating Git repository'

- powershell: |
    cd c:/IntegrationProject
    npm install
  displayName: 'Installing dependencies'
  
- powershell: |
    node .\syncReceiver.js
  displayName: 'Running application'


